/**:
  ros__parameters:
      # Configuration parameters that should be applied:
    topic: '/triton_right/images'  # Your custom topic name
    pixelformat: 'rgb8'           # Example: Set pixel format
    gain: 10.0                    # Example: Set gain
    exposure_time: 60000.0        # Example: Set exposure (60 ms)
    trigger_mode: False           # Example: Set trigger mode
    
    # ROS 2 Standard Parameters (if needed by your driver)
    qos_reliability: 'best_effort'
    acquisition_frame_rate: 5.0   # Example: Set frame rate